apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: api-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Отключаем кэширование для всех ответов
    nginx.ingress.kubernetes.io/proxy-no-cache: "1"
    nginx.ingress.kubernetes.io/proxy-cache: "off"
    # Сохраняем все headers от backend
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Cache-Control: no-cache, no-store, must-revalidate";
      more_set_headers "Pragma: no-cache";
      more_set_headers "Expires: 0";
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - minemap.pp.ua
      secretName: api-gateway-tls

  rules:
    - host: minemap.pp.ua
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000
